### ISSUE TITLE
Ability to do console.log('var', var)

### ISSUE THREAD

**Issue by sdhayalan** [dhruv0127/quickpaste-console-log#1]
Maybe add another keyboard shortcut so that  it will log the name of the var (whatever the selection is).

Other than that, nice extension. Thanks for creating it.

**Comment by dhruv0127** [comment]
Thanks a lot for your suggestion! We actually had this feature in[ version 0.4.0, ](https://marketplace.visualstudio.com/items?itemName=ParekhDhruv.quickpaste-console-log)but after hearing from team members, we decided to remove it for a while. 
The idea was devs will clean up their code by removing cloz and console.error after cleaning they can again start using Quick Paste. However, after seeing a drop in usage and installs, we decided to bring it back. 

Your feedback was perfect📈, and we're glad to share that **this feature is now available again** in [version 0.7.0](https://marketplace.visualstudio.com/items?itemName=ParekhDhruv.quickpaste-console-log) and later! 🎯✨
